### ISSUE TITLE
You shouldn't have to click sign in twice when accessToken is expired but the refreshToken is valid

### ISSUE THREAD

**Issue by jorunfa** [telenordigital/TelenorConnectIosHelloWorld#2]

**Comment by RAGOpoR** [comment]
@jorunfa How can I help you contribute this?

**Comment by jorunfa** [comment]
@RAGOpoR: Hi! Sorry for the slow reply, was away on vacation. Please note that this isn't an issue with the SDK itself, but rather the example app for it, I think.

If I remember correctly the problem is for the view to know that the auth status has changed, since it normally uses [viewDidAppear](https://github.com/telenordigital/TelenorConnectIosHelloWorld/blob/master/TelenorConnectIosHelloWorld/SignInViewController.swift#L31) to get notified of this, but that function will never be called in this scenario, as no WebView or broswer will be started and later dismissed.

So the issue is making it work in both scenarios, without calling `performSegueWithIdentifier` twice in the edge scenarios.

**Comment by RAGOpoR** [comment]
@jorunfa I have other question not related to this issue can we discuss here or some where else ?

**Comment by htarwara6245** [comment]
Can you please take a look at this : [https://github.com/telenordigital/connect-ios-sdk/issues/16](url)
